// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: internal/api/proto/V1/login_data/login_data.proto

package login_data

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login    string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	EntryId  string `protobuf:"bytes,3,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
}

func (x *LoginDataRequest) Reset() {
	*x = LoginDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_proto_V1_login_data_login_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginDataRequest) ProtoMessage() {}

func (x *LoginDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_V1_login_data_login_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginDataRequest.ProtoReflect.Descriptor instead.
func (*LoginDataRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_V1_login_data_login_data_proto_rawDescGZIP(), []int{0}
}

func (x *LoginDataRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *LoginDataRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginDataRequest) GetEntryId() string {
	if x != nil {
		return x.EntryId
	}
	return ""
}

type LoginDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *LoginDataResponse) Reset() {
	*x = LoginDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_proto_V1_login_data_login_data_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginDataResponse) ProtoMessage() {}

func (x *LoginDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_V1_login_data_login_data_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginDataResponse.ProtoReflect.Descriptor instead.
func (*LoginDataResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_V1_login_data_login_data_proto_rawDescGZIP(), []int{1}
}

func (x *LoginDataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetLoginDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntryId string `protobuf:"bytes,1,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
}

func (x *GetLoginDataRequest) Reset() {
	*x = GetLoginDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_proto_V1_login_data_login_data_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLoginDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoginDataRequest) ProtoMessage() {}

func (x *GetLoginDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_V1_login_data_login_data_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoginDataRequest.ProtoReflect.Descriptor instead.
func (*GetLoginDataRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_V1_login_data_login_data_proto_rawDescGZIP(), []int{2}
}

func (x *GetLoginDataRequest) GetEntryId() string {
	if x != nil {
		return x.EntryId
	}
	return ""
}

type GetLoginDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login    string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	EntryId  string `protobuf:"bytes,3,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	Id       string `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetLoginDataResponse) Reset() {
	*x = GetLoginDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_proto_V1_login_data_login_data_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLoginDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoginDataResponse) ProtoMessage() {}

func (x *GetLoginDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_V1_login_data_login_data_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoginDataResponse.ProtoReflect.Descriptor instead.
func (*GetLoginDataResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_V1_login_data_login_data_proto_rawDescGZIP(), []int{3}
}

func (x *GetLoginDataResponse) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *GetLoginDataResponse) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *GetLoginDataResponse) GetEntryId() string {
	if x != nil {
		return x.EntryId
	}
	return ""
}

func (x *GetLoginDataResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type EditLoginDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login    string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	EntryId  string `protobuf:"bytes,3,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	Id       string `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *EditLoginDataRequest) Reset() {
	*x = EditLoginDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_proto_V1_login_data_login_data_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditLoginDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditLoginDataRequest) ProtoMessage() {}

func (x *EditLoginDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_V1_login_data_login_data_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditLoginDataRequest.ProtoReflect.Descriptor instead.
func (*EditLoginDataRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_V1_login_data_login_data_proto_rawDescGZIP(), []int{4}
}

func (x *EditLoginDataRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *EditLoginDataRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *EditLoginDataRequest) GetEntryId() string {
	if x != nil {
		return x.EntryId
	}
	return ""
}

func (x *EditLoginDataRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteLoginDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntryId string `protobuf:"bytes,1,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
}

func (x *DeleteLoginDataRequest) Reset() {
	*x = DeleteLoginDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_proto_V1_login_data_login_data_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteLoginDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLoginDataRequest) ProtoMessage() {}

func (x *DeleteLoginDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_V1_login_data_login_data_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLoginDataRequest.ProtoReflect.Descriptor instead.
func (*DeleteLoginDataRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_V1_login_data_login_data_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteLoginDataRequest) GetEntryId() string {
	if x != nil {
		return x.EntryId
	}
	return ""
}

type GetAllLoginDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllLoginDataRequest) Reset() {
	*x = GetAllLoginDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_proto_V1_login_data_login_data_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllLoginDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllLoginDataRequest) ProtoMessage() {}

func (x *GetAllLoginDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_V1_login_data_login_data_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllLoginDataRequest.ProtoReflect.Descriptor instead.
func (*GetAllLoginDataRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_V1_login_data_login_data_proto_rawDescGZIP(), []int{6}
}

type GetAllLoginDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*GetLoginDataResponse `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *GetAllLoginDataResponse) Reset() {
	*x = GetAllLoginDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_proto_V1_login_data_login_data_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllLoginDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllLoginDataResponse) ProtoMessage() {}

func (x *GetAllLoginDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_V1_login_data_login_data_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllLoginDataResponse.ProtoReflect.Descriptor instead.
func (*GetAllLoginDataResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_V1_login_data_login_data_proto_rawDescGZIP(), []int{7}
}

func (x *GetAllLoginDataResponse) GetItems() []*GetLoginDataResponse {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_internal_api_proto_V1_login_data_login_data_proto protoreflect.FileDescriptor

var file_internal_api_proto_V1_login_data_login_data_proto_rawDesc = []byte{
	0x0a, 0x31, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x56, 0x31, 0x2f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x64, 0x61,
	0x74, 0x61, 0x2f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x76, 0x31, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x5f, 0x0a, 0x10, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x74, 0x72,
	0x79, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72,
	0x79, 0x49, 0x64, 0x22, 0x2d, 0x0a, 0x11, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x22, 0x30, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x74,
	0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x74,
	0x72, 0x79, 0x49, 0x64, 0x22, 0x73, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67,
	0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x19,
	0x0a, 0x08, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x73, 0x0a, 0x14, 0x45, 0x64, 0x69,
	0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x49, 0x64, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x33,
	0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x74, 0x72,
	0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72,
	0x79, 0x49, 0x64, 0x22, 0x18, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x54, 0x0a,
	0x17, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x76, 0x31, 0x2e, 0x6c, 0x6f, 0x67,
	0x69, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x05, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x32, 0xd5, 0x03, 0x0a, 0x10, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x44, 0x61, 0x74,
	0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x52, 0x0a, 0x0d, 0x53, 0x61, 0x76, 0x65,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1f, 0x2e, 0x76, 0x31, 0x2e, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x76, 0x31, 0x2e,
	0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x57, 0x0a, 0x0c,
	0x47, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x12, 0x22, 0x2e, 0x76,
	0x31, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x47, 0x65, 0x74,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x23, 0x2e, 0x76, 0x31, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61,
	0x2e, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x56, 0x0a, 0x0d, 0x45, 0x64, 0x69, 0x74, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x12, 0x23, 0x2e, 0x76, 0x31, 0x2e, 0x6c, 0x6f, 0x67, 0x69,
	0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x76, 0x31,
	0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5a, 0x0a,
	0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x25, 0x2e, 0x76, 0x31, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x76, 0x31, 0x2e, 0x6c, 0x6f, 0x67,
	0x69, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x60, 0x0a, 0x0f, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x12, 0x25, 0x2e, 0x76,
	0x31, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x76, 0x31, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x64,
	0x61, 0x74, 0x61, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x23, 0x5a, 0x21, 0x67,
	0x6f, 0x70, 0x68, 0x4b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x56, 0x31, 0x2f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_api_proto_V1_login_data_login_data_proto_rawDescOnce sync.Once
	file_internal_api_proto_V1_login_data_login_data_proto_rawDescData = file_internal_api_proto_V1_login_data_login_data_proto_rawDesc
)

func file_internal_api_proto_V1_login_data_login_data_proto_rawDescGZIP() []byte {
	file_internal_api_proto_V1_login_data_login_data_proto_rawDescOnce.Do(func() {
		file_internal_api_proto_V1_login_data_login_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_api_proto_V1_login_data_login_data_proto_rawDescData)
	})
	return file_internal_api_proto_V1_login_data_login_data_proto_rawDescData
}

var file_internal_api_proto_V1_login_data_login_data_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_internal_api_proto_V1_login_data_login_data_proto_goTypes = []any{
	(*LoginDataRequest)(nil),        // 0: v1.login_data.LoginDataRequest
	(*LoginDataResponse)(nil),       // 1: v1.login_data.LoginDataResponse
	(*GetLoginDataRequest)(nil),     // 2: v1.login_data.GetLoginDataRequest
	(*GetLoginDataResponse)(nil),    // 3: v1.login_data.GetLoginDataResponse
	(*EditLoginDataRequest)(nil),    // 4: v1.login_data.EditLoginDataRequest
	(*DeleteLoginDataRequest)(nil),  // 5: v1.login_data.DeleteLoginDataRequest
	(*GetAllLoginDataRequest)(nil),  // 6: v1.login_data.GetAllLoginDataRequest
	(*GetAllLoginDataResponse)(nil), // 7: v1.login_data.GetAllLoginDataResponse
}
var file_internal_api_proto_V1_login_data_login_data_proto_depIdxs = []int32{
	3, // 0: v1.login_data.GetAllLoginDataResponse.items:type_name -> v1.login_data.GetLoginDataResponse
	0, // 1: v1.login_data.LoginDataService.SaveLoginData:input_type -> v1.login_data.LoginDataRequest
	2, // 2: v1.login_data.LoginDataService.GetLoginData:input_type -> v1.login_data.GetLoginDataRequest
	4, // 3: v1.login_data.LoginDataService.EditLoginData:input_type -> v1.login_data.EditLoginDataRequest
	5, // 4: v1.login_data.LoginDataService.DeleteLoginData:input_type -> v1.login_data.DeleteLoginDataRequest
	6, // 5: v1.login_data.LoginDataService.GetAllLoginData:input_type -> v1.login_data.GetAllLoginDataRequest
	1, // 6: v1.login_data.LoginDataService.SaveLoginData:output_type -> v1.login_data.LoginDataResponse
	3, // 7: v1.login_data.LoginDataService.GetLoginData:output_type -> v1.login_data.GetLoginDataResponse
	1, // 8: v1.login_data.LoginDataService.EditLoginData:output_type -> v1.login_data.LoginDataResponse
	1, // 9: v1.login_data.LoginDataService.DeleteLoginData:output_type -> v1.login_data.LoginDataResponse
	7, // 10: v1.login_data.LoginDataService.GetAllLoginData:output_type -> v1.login_data.GetAllLoginDataResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_api_proto_V1_login_data_login_data_proto_init() }
func file_internal_api_proto_V1_login_data_login_data_proto_init() {
	if File_internal_api_proto_V1_login_data_login_data_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_api_proto_V1_login_data_login_data_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*LoginDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_proto_V1_login_data_login_data_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*LoginDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_proto_V1_login_data_login_data_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetLoginDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_proto_V1_login_data_login_data_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetLoginDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_proto_V1_login_data_login_data_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*EditLoginDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_proto_V1_login_data_login_data_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteLoginDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_proto_V1_login_data_login_data_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetAllLoginDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_proto_V1_login_data_login_data_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*GetAllLoginDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_api_proto_V1_login_data_login_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_api_proto_V1_login_data_login_data_proto_goTypes,
		DependencyIndexes: file_internal_api_proto_V1_login_data_login_data_proto_depIdxs,
		MessageInfos:      file_internal_api_proto_V1_login_data_login_data_proto_msgTypes,
	}.Build()
	File_internal_api_proto_V1_login_data_login_data_proto = out.File
	file_internal_api_proto_V1_login_data_login_data_proto_rawDesc = nil
	file_internal_api_proto_V1_login_data_login_data_proto_goTypes = nil
	file_internal_api_proto_V1_login_data_login_data_proto_depIdxs = nil
}
