// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.12.4
// source: internal/api/proto/V1/text_data/text_data.proto

package text_data

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	TextDataService_SaveTextData_FullMethodName   = "/v1.text_data.TextDataService/SaveTextData"
	TextDataService_GetTextData_FullMethodName    = "/v1.text_data.TextDataService/GetTextData"
	TextDataService_EditTextData_FullMethodName   = "/v1.text_data.TextDataService/EditTextData"
	TextDataService_DeleteTextData_FullMethodName = "/v1.text_data.TextDataService/DeleteTextData"
)

// TextDataServiceClient is the client API for TextDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TextDataServiceClient interface {
	SaveTextData(ctx context.Context, in *TextDataRequest, opts ...grpc.CallOption) (*TextDataResponse, error)
	GetTextData(ctx context.Context, in *GetTextDataRequest, opts ...grpc.CallOption) (*GetTextDataResponse, error)
	EditTextData(ctx context.Context, in *EditTextDataRequest, opts ...grpc.CallOption) (*TextDataResponse, error)
	DeleteTextData(ctx context.Context, in *DeleteTextDataRequest, opts ...grpc.CallOption) (*TextDataResponse, error)
}

type textDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTextDataServiceClient(cc grpc.ClientConnInterface) TextDataServiceClient {
	return &textDataServiceClient{cc}
}

func (c *textDataServiceClient) SaveTextData(ctx context.Context, in *TextDataRequest, opts ...grpc.CallOption) (*TextDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TextDataResponse)
	err := c.cc.Invoke(ctx, TextDataService_SaveTextData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *textDataServiceClient) GetTextData(ctx context.Context, in *GetTextDataRequest, opts ...grpc.CallOption) (*GetTextDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTextDataResponse)
	err := c.cc.Invoke(ctx, TextDataService_GetTextData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *textDataServiceClient) EditTextData(ctx context.Context, in *EditTextDataRequest, opts ...grpc.CallOption) (*TextDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TextDataResponse)
	err := c.cc.Invoke(ctx, TextDataService_EditTextData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *textDataServiceClient) DeleteTextData(ctx context.Context, in *DeleteTextDataRequest, opts ...grpc.CallOption) (*TextDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TextDataResponse)
	err := c.cc.Invoke(ctx, TextDataService_DeleteTextData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TextDataServiceServer is the server API for TextDataService service.
// All implementations must embed UnimplementedTextDataServiceServer
// for forward compatibility
type TextDataServiceServer interface {
	SaveTextData(context.Context, *TextDataRequest) (*TextDataResponse, error)
	GetTextData(context.Context, *GetTextDataRequest) (*GetTextDataResponse, error)
	EditTextData(context.Context, *EditTextDataRequest) (*TextDataResponse, error)
	DeleteTextData(context.Context, *DeleteTextDataRequest) (*TextDataResponse, error)
	mustEmbedUnimplementedTextDataServiceServer()
}

// UnimplementedTextDataServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTextDataServiceServer struct {
}

func (UnimplementedTextDataServiceServer) SaveTextData(context.Context, *TextDataRequest) (*TextDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveTextData not implemented")
}
func (UnimplementedTextDataServiceServer) GetTextData(context.Context, *GetTextDataRequest) (*GetTextDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTextData not implemented")
}
func (UnimplementedTextDataServiceServer) EditTextData(context.Context, *EditTextDataRequest) (*TextDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditTextData not implemented")
}
func (UnimplementedTextDataServiceServer) DeleteTextData(context.Context, *DeleteTextDataRequest) (*TextDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTextData not implemented")
}
func (UnimplementedTextDataServiceServer) mustEmbedUnimplementedTextDataServiceServer() {}

// UnsafeTextDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TextDataServiceServer will
// result in compilation errors.
type UnsafeTextDataServiceServer interface {
	mustEmbedUnimplementedTextDataServiceServer()
}

func RegisterTextDataServiceServer(s grpc.ServiceRegistrar, srv TextDataServiceServer) {
	s.RegisterService(&TextDataService_ServiceDesc, srv)
}

func _TextDataService_SaveTextData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TextDataServiceServer).SaveTextData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TextDataService_SaveTextData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TextDataServiceServer).SaveTextData(ctx, req.(*TextDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TextDataService_GetTextData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTextDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TextDataServiceServer).GetTextData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TextDataService_GetTextData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TextDataServiceServer).GetTextData(ctx, req.(*GetTextDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TextDataService_EditTextData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditTextDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TextDataServiceServer).EditTextData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TextDataService_EditTextData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TextDataServiceServer).EditTextData(ctx, req.(*EditTextDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TextDataService_DeleteTextData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTextDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TextDataServiceServer).DeleteTextData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TextDataService_DeleteTextData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TextDataServiceServer).DeleteTextData(ctx, req.(*DeleteTextDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TextDataService_ServiceDesc is the grpc.ServiceDesc for TextDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TextDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.text_data.TextDataService",
	HandlerType: (*TextDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveTextData",
			Handler:    _TextDataService_SaveTextData_Handler,
		},
		{
			MethodName: "GetTextData",
			Handler:    _TextDataService_GetTextData_Handler,
		},
		{
			MethodName: "EditTextData",
			Handler:    _TextDataService_EditTextData_Handler,
		},
		{
			MethodName: "DeleteTextData",
			Handler:    _TextDataService_DeleteTextData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/api/proto/V1/text_data/text_data.proto",
}
